[package]
name = "cryptography-pals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
hex = "0.4.3"
itertools = "0.10.5"
openssl = "0.10"
rand = "0.8.5"
